baseURL = 'https://fluffydistortion.netlify.app'
theme = "PaperMod"
languageCode = 'ja'
defaultContentLanguage = "ja"
timezone = "Asia/Tokyo"
title = 'ふわふわディストーション'

[taxonomies]
  category = "categories"
  tag = "tags"


[menu]
    [[menu.main]]
        name = "Home"
        url = "/"
        weight = 10
    [[menu.main]]
        name = "About"
        url = "/about/"
        weight = 20
    [[menu.main]]
        name = "Posts"
        url = "/posts/"
        weight = 30
    [[menu.main]]
        identifier = "categories"
        name = "Categories"
        url = "/categories/"
        weight = 40
    [[menu.main]]
        identifier = "tags"
        name = "Tags"
        url = "/tags/"
        weight = 50

[params]
  author = "yata"
  description = "趣味や考えをつらつら書き綴る場所"
  ShowReadingTime = true
  ShowShareButtons = false
  ShowTags = true
  ShowCategories = true
  ShowPostNavLinks = true
  ShowPostMeta = true


    [[params.socialIcons]]
        name = "twitter"
        url = "https://x.com/yata_3o1"

    [params.profileMode]
        enabled = true
        title = "yata"   # プロフィールカードに出る名前
        subtitle = "メタ、シニカル、ナンセンス" # キャッチコピー
        imageUrl = "images/icon.webp"  # アバター画像パス（static/配下）
        imageWidth = 200  # アバターの幅（px）
        imageHeight = 200  # アバターの高さ（px）
        buttons = [
        { name = "記事一覧", url = "/posts/" }
        ]

    [param.share]
        enable = true
        Twitter = true